### ISSUE TITLE
Map display crashes when marker is present 

### ISSUE THREAD

**Issue by Stvad** [RoamJS/mapbox#1]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/81347/206678764-f53b48fe-824a-4c8b-996d-ff929a9e7967.png">

Configuration producing the crash:
```
- {{maps}}
    - Center
        - 37.761013,-122.4216972
    - Markers
        - [[Dandelion Chocolate]]
            - 37.761013,-122.4216972
```

**Comment by dvargasfuertes** [comment]
fix has been under review: https://github.com/Roam-Research/roam-depot/pull/380
